# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test

build-job:
  stage: build
  image: registry.gitlab.rylanswebsite.com/rylan-meilutis/prusa-firmware-patches:latest
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './secure_files'
  script:
    - mkdir secure_files
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - mv secure_files/* .
    - bash ci-build.sh v6.2.6 mk4,xl,mk3.5,mini
    - bash ci-build.sh v6.3.4 coreone
  tags: [ "docker_build" ]

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
